// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTcWeltolkAutoreplyTasks = "tc_weltolk_autoreply_tasks"

// TcWeltolkAutoreplyTasks mapped from table <tc_weltolk_autoreply_tasks>
type TcWeltolkAutoreplyTasks struct {
	ID             int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UID            int32  `gorm:"column:uid;type:int;not null" json:"uid"`
	Pid            int32  `gorm:"column:pid;type:int;not null;default:0" json:"pid"`
	Fname          string `gorm:"column:fname;type:varchar(255);not null" json:"fname"`
	Tid            int64  `gorm:"column:tid;type:bigint;not null" json:"tid"`
	LastFloor      int32  `gorm:"column:last_floor;type:int;default:0" json:"last_floor"`
	LastRepliedPid int64  `gorm:"column:last_replied_pid;type:bigint;not null;default:0" json:"last_replied_pid"`
	LastReplyTime  int32  `gorm:"column:last_reply_time;type:int;default:0" json:"last_reply_time"`
	LastStatus     string `gorm:"column:last_status;type:varchar(32);default:''" json:"last_status"`
	LastError      string `gorm:"column:last_error;type:text" json:"last_error"`
	LastCheckTime  int32  `gorm:"column:last_check_time;type:int;default:0" json:"last_check_time"`
	Log            string `gorm:"column:log;type:text" json:"log"`
	ReplyContent   string `gorm:"column:reply_content;type:text" json:"reply_content"`
	ReplyInterval  int32  `gorm:"column:reply_interval;type:int;default:300" json:"reply_interval"`
	ReplyProbability int32 `gorm:"column:reply_probability;type:int;default:100" json:"reply_probability"`
	Enabled        int32  `gorm:"column:enabled;type:tinyint;default:1" json:"enabled"`
	RetryCount     int32  `gorm:"column:retry_count;type:int;default:0" json:"retry_count"`
	TriggerMode    string `gorm:"column:trigger_mode;type:varchar(20);not null;default:'new_floor'" json:"trigger_mode"`
	ReplyTarget    string `gorm:"column:reply_target;type:varchar(20);not null;default:'floor'" json:"reply_target"`
	AllowReplied   int32  `gorm:"column:allow_replied;type:tinyint;not null;default:0" json:"allow_replied"`
	MatchKeywords  string `gorm:"column:match_keywords;type:text" json:"match_keywords"`
}

// TableName TcWeltolkAutoreplyTasks's table name
func (*TcWeltolkAutoreplyTasks) TableName() string {
	return TableNameTcWeltolkAutoreplyTasks
}
